### ISSUE TITLE
title_attributes conversion commented out in preprocess node hook

### ISSUE THREAD

**Issue by elisseck** [backdrop-contrib/d7compatible#5]
@jenlampton do you remember if there is a reason why this is commented out (as opposed to either running or removed entirely)? I can create a PR if there isn't one: https://github.com/backdrop-contrib/d7compatible/blob/e68e5c94b7833c4da9c306057967c782ad444454/template.php#L53

I am seeing warnings on node pages for ported themes using this compatibility layer unless I un-comment that line:

`Warning: Undefined variable $title_attributes in include() (line 88 of /var/www/backdrop.local/web/themes/d7compatible/templates/node.tpl.php).`

**Comment by jenlampton** [comment]
No, that's probably a mistake :/ Thank you for finding it!

**Comment by jenlampton** [comment]
FIxed in `6194c869c77518de8b5fd58b65220db451d3fadb` and should be included in https://github.com/backdrop-contrib/d7compatible/releases/tag/1.x-1.0.2
